INSERT INTO ORGANIZATION (NAME, ADDRESS, PHONE) VALUES ('IBM', 'New York', '657-890-9090');
INSERT INTO ORGANIZATION (NAME, ADDRESS, PHONE) VALUES ('Microsoft', 'Redmond', '657-890-6373');
INSERT INTO ORGANIZATION (NAME, ADDRESS, PHONE) VALUES ('Google', 'Bay Area', '657-890-9270');
INSERT INTO ORGANIZATION (NAME, ADDRESS, PHONE) VALUES ('Amazon', 'Seattle', '657-890-9091');


INSERT INTO USER_ENTITY (LAST_NAME, FIRST_NAME, EMAIL, ADDRESS, PHONE) VALUES('Adams', 'Roy', 'radams1v@xinhuanet.com', '2872 Marquette Street',  '1-(235)314-9823');
INSERT INTO USER_ENTITY (LAST_NAME, FIRST_NAME, EMAIL, ADDRESS, PHONE) VALUES('Bell', 'David', 'dbell2l@wp.com',  '5205 Vera Junction', '8-(035)412-4547');
INSERT INTO USER_ENTITY (LAST_NAME, FIRST_NAME, EMAIL, ADDRESS, PHONE) VALUES('Campbell', 'Jessica', 'jcampbell2i@cpanel.net',  '7963 Ohio Alley',  '0-(150)386-2177');
INSERT INTO USER_ENTITY (LAST_NAME, FIRST_NAME, EMAIL, ADDRESS, PHONE) VALUES('Carpenter', 'Pamela', 'pcarpenterj@china.com',  '661 Karstens Road', '6-(268)816-2465');
INSERT INTO USER_ENTITY (LAST_NAME, FIRST_NAME, EMAIL, ADDRESS, PHONE) VALUES('Meyer', 'Lisa', 'lmeyer2k@ycombinator.com',  '6 Mallory Circle',  '6-(321)779-8895');
INSERT INTO USER_ENTITY (LAST_NAME, FIRST_NAME, EMAIL, ADDRESS, PHONE) VALUES('Wright', 'Joan', 'jwright1q@phoca.cz', '55 Dawn Parkway', '7-(830)749-3794');
INSERT INTO USER_ENTITY (LAST_NAME, FIRST_NAME, EMAIL, ADDRESS, PHONE) VALUES('Young', 'Judith', 'jyoung11@goodreads.com', '2 Sachtjen Parkway',  '9-(659)879-6466');

INSERT INTO ASSOCIATION (ORGANIZATION_ID, USER_ID) VALUES ((SELECT ORGANIZATION_ID FROM ORGANIZATION WHERE name = 'IBM'), (SELECT USER_ID FROM USER_ENTITY WHERE LAST_NAME = 'Adams'));
INSERT INTO ASSOCIATION (ORGANIZATION_ID, USER_ID) VALUES ((SELECT ORGANIZATION_ID FROM ORGANIZATION WHERE name = 'Microsoft'), (SELECT USER_ID FROM USER_ENTITY WHERE LAST_NAME = 'Adams'));
INSERT INTO ASSOCIATION (ORGANIZATION_ID, USER_ID) VALUES ((SELECT ORGANIZATION_ID FROM ORGANIZATION WHERE name = 'Microsoft'), (SELECT USER_ID FROM USER_ENTITY WHERE LAST_NAME = 'Young'));
INSERT INTO ASSOCIATION (ORGANIZATION_ID, USER_ID) VALUES ((SELECT ORGANIZATION_ID FROM ORGANIZATION WHERE name = 'Google'), (SELECT USER_ID FROM USER_ENTITY WHERE LAST_NAME = 'Meyer'));